name: Release Python

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.9'
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  create-sdist:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [connectorx]

    env:
      SED_INPLACE: ${{ matrix.os == 'macos-13' && '-i ''''' || '-i'}}

    steps:
      - uses: actions/checkout@v4

      # Avoid potential out-of-memory errors
      - name: Set swap space for Linux
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create source distribution
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: >
            --manifest-path connectorx-python/Cargo.toml
            --out dist
          before-script-linux: |
              sudo apt-get install -y libssl-dev openssl pkg-config libkrb5-dev gcc-multilib

      - name: Test sdist
        run: |
          pip install --force-reinstall --verbose dist/*.tar.gz
          python -c 'import connectorx'

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist-${{ matrix.package }}
          path: dist/*.tar.gz

  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        package: [connectorx]
        os: [ubuntu-latest, macos-13, windows-32gb-ram]
        architecture: [x86-64, aarch64]
        exclude:
          - os: windows-32gb-ram
            architecture: aarch64

    env:
      SED_INPLACE: ${{ matrix.os == 'macos-13' && '-i ''''' || '-i'}}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}

      # Avoid potential out-of-memory errors
      - name: Set swap space for Linux
        if: matrix.os == 'ubuntu-latest'
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Determine CPU features for x86-64
        id: features
        if: matrix.architecture == 'x86-64'
        run: |
          if [[ "$IS_LTS_CPU" = true ]]; then
            FEATURES=+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+cmpxchg16b
            CC_FEATURES="-msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mcx16"
          else
            TUNE_CPU=skylake
            FEATURES=+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+cmpxchg16b,+avx,+avx2,+fma,+bmi1,+bmi2,+lzcnt,+pclmulqdq,+movbe
            CC_FEATURES="-msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mcx16 -mavx -mavx2 -mfma -mbmi -mbmi2 -mlzcnt -mpclmul -mmovbe"
          fi
          echo "features=$FEATURES" >> $GITHUB_OUTPUT
          echo "tune_cpu=$TUNE_CPU" >> $GITHUB_OUTPUT
          echo "cc_features=$CC_FEATURES" >> $GITHUB_OUTPUT


      - name: Set Rust target for aarch64
        if: matrix.architecture == 'aarch64'
        id: target
        run: |
          TARGET=${{ matrix.os == 'macos-13' && 'aarch64-apple-darwin' || 'aarch64-unknown-linux-gnu'}}
          echo "target=$TARGET" >> $GITHUB_OUTPUT

      - name: Set jemalloc for aarch64 Linux
        if: matrix.architecture == 'aarch64' && matrix.os == 'ubuntu-latest'
        run: |
          echo "JEMALLOC_SYS_WITH_LG_PAGE=16" >> $GITHUB_ENV

      - name: Build wheel
        uses: PyO3/maturin-action@v1
        with:
          command: build
          target: ${{ steps.target.outputs.target }}
          args: >
            -i python3.9
            --profile dist-release
            --manifest-path connectorx-python/Cargo.toml
            --out dist
          manylinux: ${{ matrix.architecture == 'aarch64' && '2_24' || 'auto' }}
          before-script-linux: |
              if command -v apt-get >/dev/null 2>&1; then
                  echo "Detected apt-get package manager. Installing packages using apt-get..."
                  sudo apt-get update
                  sudo apt-get install -y libssl-dev openssl pkg-config libkrb5-dev gcc-multilib
                  if [ $? -eq 0 ]; then
                      echo "Packages installed successfully using apt-get."
                  else
                      echo "Failed to install packages using apt-get."
                      exit 1
                  fi

              elif command -v yum >/dev/null 2>&1; then
                  echo "Detected yum package manager. Installing packages using yum..."
                  yum update -y
                  yum install -y openssl-devel krb5-devel pkgconfig gcc openssl
                  if [ $? -eq 0 ]; then
                      echo "Packages installed successfully using yum."
                  else
                      echo "Failed to install packages using yum."
                      exit 1
                  fi
              else
                  echo "Neither apt-get nor yum package manager is available."
                  exit 1
              fi

              export LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH


      - name: Test wheel
        # Only test on x86-64 for now as this matches the runner architecture
        if: matrix.architecture == 'x86-64'
        run: |
          pip install --force-reinstall --verbose dist/*.whl
          python -c 'import connectorx'

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.package }}-${{ matrix.os }}-${{ matrix.architecture }}
          path: dist/*.whl

  # publish-to-pypi:
  #   needs: [create-sdist, build-wheels]
  #   environment:
  #     name: release-python
  #     url: https://pypi.org/project/polars
  #   runs-on: ubuntu-latest
  #   permissions:
  #     id-token: write

  #   steps:
  #     - name: Download sdists and wheels
  #       uses: actions/download-artifact@v4
  #       with:
  #         path: dist
  #         merge-multiple: true

  #     - name: Publish to PyPI
  #       if: inputs.dry-run == false
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         verbose: true

  # publish-to-github:
  #   needs: publish-to-pypi
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: ${{ inputs.sha }}

  #     - name: Download sdist
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: sdist-polars
  #         path: dist

  #     - name: Get version from Cargo.toml
  #       id: version
  #       working-directory: py-polars
  #       run: |
  #         VERSION=$(grep -m 1 -oP 'version = "\K[^"]+' Cargo.toml)
  #         if [[ "$VERSION" == *"-"* ]]; then
  #           IS_PRERELEASE=true
  #         else
  #           IS_PRERELEASE=false
  #         fi
  #         echo "version=$VERSION" >> $GITHUB_OUTPUT
  #         echo "is_prerelease=$IS_PRERELEASE" >> $GITHUB_OUTPUT

  #     - name: Create GitHub release
  #       id: github-release
  #       uses: release-drafter/release-drafter@v6
  #       with:
  #         config-name: release-drafter-python.yml
  #         name: Python Polars ${{ steps.version.outputs.version }}
  #         tag: py-${{ steps.version.outputs.version }}
  #         version: ${{ steps.version.outputs.version }}
  #         prerelease: ${{ steps.version.outputs.is_prerelease }}
  #         commitish: ${{ inputs.sha || github.sha }}
  #         disable-autolabeler: true
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Upload sdist to GitHub release
  #       run: gh release upload $TAG $FILES --clobber
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         TAG: ${{ steps.github-release.outputs.tag_name }}
  #         FILES: dist/polars-*.tar.gz

  #     - name: Publish GitHub release
  #       if: inputs.dry-run == false
  #       run: gh release edit $TAG --draft=false
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         TAG: ${{ steps.github-release.outputs.tag_name }}

  #     - name: Trigger other workflows related to the release
  #       if: inputs.dry-run == false
  #       uses: peter-evans/repository-dispatch@v3
  #       with:
  #         event-type: python-release
  #         client-payload: >
  #           {
  #             "version": "${{ steps.version.outputs.version }}",
  #             "is_prerelease": "${{ steps.version.outputs.is_prerelease }}",
  #             "tag": "${{ steps.github-release.outputs.tag_name }}",
  #             "sha": "${{ inputs.sha || github.sha }}"
  #           }