name: aarch64-test

on:
  push:

jobs:
 linux-aarch:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_aarch64
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"] 
          
    steps:
      - uses: actions/checkout@v4

      - name: Set swap space for Linux
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist -m connectorx-python/Cargo.toml -i python${{ matrix.python-version }}
          before-script-linux: |
            apt-get update -y
            apt-get install -y libssl-dev openssl pkg-config libkrb5-dev gcc-multilib 

      - uses: uraimo/run-on-arch-action@v2.8.1
        name: Install built wheel
        with:      
          run: |
            python3 -c "import connectorx"


      - uses: actions/upload-artifact@v3
        with:
          name: "aarch-test"
          path: connectorx-python/target/wheels/*.whl