name: aarch64-test

on:
  push:

jobs:
 linux-aarch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      matrix:
        os: [ubuntu-latest]
        architecture: [aarch64]
          
    steps:
      - uses: actions/checkout@v4

      - name: Set swap space for Linux
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.71.1
          components: rustfmt
          target: aarch64-unknown-linux-gnu
          default: true

      - name: Set jemalloc for aarch64 Linux
        if: matrix.architecture == 'aarch64' && matrix.os == 'ubuntu-latest'
        run: |
          echo "JEMALLOC_SYS_WITH_LG_PAGE=16" >> $GITHUB_ENV

      - name: Build wheel
        uses: PyO3/maturin-action@v1
        with:
          manylinux: 2_24
          target: aarch64-unknown-linux-gnu
          rust-toolchain: 1.71.1
          command: build
          args: -m connectorx-python/Cargo.toml -i python --release --features integrated-auth-gssapi
        env:
          SQLITE3_STATIC: 1

      - name: Copy j4rs dependencies into dist
        run: |
          cp -rf connectorx-python/target/release/jassets connectorx-python/connectorx/dependencies

      # rebuild the wheel to incorporate j4rs dependencies
      - name: Build wheel
        uses: PyO3/maturin-action@v1
        with:
          manylinux: 2_24
          target: aarch64-unknown-linux-gnu
          rust-toolchain: 1.71.1
          command: build
          args: -m connectorx-python/Cargo.toml -i python --release --features integrated-auth-gssapi
        env:
          SQLITE3_STATIC: 1

      - uses: actions/upload-artifact@v3
        with:
          name: "aarch-test"
          path: connectorx-python/target/wheels/*.whl